export const desktopAppMenuItems = [
  { commandId: 'file:about' },
  { type: 'separator' },
  { role: 'hide' },
  { role: 'hideOthers' },
  { role: 'unhide' },
  { type: 'separator' },
  { role: 'quit' },
];

export const desktopMenuGroups = [
  {
    label: '파일',
    items: [
      { commandId: 'file:new-doc', accelerator: 'CommandOrControl+N' },
      { commandId: 'file:open', accelerator: 'CommandOrControl+O' },
      { commandId: 'file:save', accelerator: 'CommandOrControl+S' },
      { type: 'separator' },
      { commandId: 'file:page-setup', accelerator: 'F7' },
      { commandId: 'file:print', accelerator: 'CommandOrControl+P' },
      { type: 'separator' },
      { type: 'recent' },
      { type: 'separator' },
      { commandId: 'file:about' },
    ],
  },
  {
    label: '편집',
    items: [
      { commandId: 'edit:undo', accelerator: 'CommandOrControl+Z' },
      { commandId: 'edit:redo', accelerator: 'CommandOrControl+Shift+Z' },
      { type: 'separator' },
      { commandId: 'edit:cut', accelerator: 'CommandOrControl+X' },
      { commandId: 'edit:copy', accelerator: 'CommandOrControl+C' },
      { commandId: 'edit:paste', accelerator: 'CommandOrControl+V' },
      { commandId: 'edit:format-copy' },
      { type: 'separator' },
      { commandId: 'edit:delete' },
      { commandId: 'edit:select-all', accelerator: 'CommandOrControl+A' },
      { type: 'separator' },
      { commandId: 'edit:find', accelerator: 'CommandOrControl+F' },
      { commandId: 'edit:find-replace', accelerator: 'CommandOrControl+F2' },
      { commandId: 'edit:find-again', accelerator: 'CommandOrControl+L' },
      { commandId: 'edit:goto', accelerator: 'Option+G' },
      { commandId: 'field:edit' },
      { commandId: 'field:remove' },
    ],
  },
  {
    label: '보기',
    items: [
      { commandId: 'view:zoom-in', accelerator: 'CommandOrControl+=' },
      { commandId: 'view:zoom-out', accelerator: 'CommandOrControl+-' },
      { type: 'separator' },
      { commandId: 'view:zoom-fit-page' },
      { commandId: 'view:zoom-fit-width' },
      { type: 'separator' },
      { commandId: 'view:zoom-50' },
      { commandId: 'view:zoom-75' },
      { commandId: 'view:zoom-100', accelerator: 'CommandOrControl+0' },
      { commandId: 'view:zoom-125' },
      { commandId: 'view:zoom-150' },
      { commandId: 'view:zoom-200' },
      { commandId: 'view:zoom-300' },
      { type: 'separator' },
      { commandId: 'view:ctrl-mark' },
      { commandId: 'view:para-mark' },
      { commandId: 'view:border-transparent' },
      { commandId: 'view:toggle-clip' },
      { commandId: 'view:grid-settings' },
      { type: 'separator' },
      { commandId: 'view:toolbox-basic' },
      { commandId: 'view:toolbox-format' },
    ],
  },
  {
    label: '입력',
    items: [
      { commandId: 'insert:shape' },
      { commandId: 'insert:image' },
      { commandId: 'insert:textbox' },
      { commandId: 'insert:field' },
      { type: 'separator' },
      { commandId: 'insert:footnote' },
      { commandId: 'insert:endnote' },
      { type: 'separator' },
      { commandId: 'insert:symbols', accelerator: 'Option+F10' },
      { commandId: 'insert:bookmark' },
      { commandId: 'insert:hyperlink' },
      { type: 'separator' },
      { commandId: 'insert:picture-props' },
      { commandId: 'insert:equation-edit' },
      { commandId: 'insert:caption-toggle' },
      { type: 'separator' },
      { commandId: 'insert:rotate-cw' },
      { commandId: 'insert:rotate-ccw' },
      { commandId: 'insert:flip-horz' },
      { commandId: 'insert:flip-vert' },
      { type: 'separator' },
      { commandId: 'insert:picture-delete' },
    ],
  },
  {
    label: '서식',
    items: [
      { commandId: 'format:bold', accelerator: 'CommandOrControl+B' },
      { commandId: 'format:italic', accelerator: 'CommandOrControl+I' },
      { commandId: 'format:underline', accelerator: 'CommandOrControl+U' },
      { type: 'separator' },
      { commandId: 'format:char-shape', accelerator: 'Option+L' },
      { commandId: 'format:para-shape', accelerator: 'Option+T' },
      { type: 'separator' },
      { commandId: 'format:para-num-shape' },
      { commandId: 'format:bullet-shape' },
      { type: 'separator' },
      { commandId: 'format:level-increase', accelerator: 'CommandOrControl+-' },
      { commandId: 'format:level-decrease', accelerator: 'CommandOrControl+=' },
      { type: 'separator' },
      { commandId: 'format:font-size-increase', accelerator: 'Option+Shift+E' },
      { commandId: 'format:font-size-decrease', accelerator: 'Option+Shift+R' },
      { type: 'separator' },
      { commandId: 'format:align-left', accelerator: 'CommandOrControl+Shift+L' },
      { commandId: 'format:align-center', accelerator: 'Option+Shift+C' },
      { commandId: 'format:align-right', accelerator: 'Option+Shift+H' },
      { commandId: 'format:align-justify', accelerator: 'CommandOrControl+Shift+M' },
      { commandId: 'format:align-distribute', accelerator: 'Option+Shift+D' },
      { type: 'separator' },
      { commandId: 'format:line-spacing-increase', accelerator: 'Option+Shift+Z' },
      { commandId: 'format:line-spacing-decrease', accelerator: 'Option+Shift+A' },
      { type: 'separator' },
      { commandId: 'format:style-dialog', accelerator: 'F6' },
      { type: 'separator' },
      { commandId: 'format:object-properties' },
    ],
  },
  {
    label: '쪽',
    items: [
      { commandId: 'page:setup', accelerator: 'F7' },
      { type: 'separator' },
      { commandId: 'page:header-create' },
      { commandId: 'page:footer-create' },
      { commandId: 'page:headerfooter-close' },
      { commandId: 'page:headerfooter-delete' },
      { commandId: 'page:headerfooter-prev' },
      { commandId: 'page:headerfooter-next' },
      { commandId: 'page:hide-headerfooter' },
      { commandId: 'page:new-page-num' },
      { commandId: 'page:hide-current' },
      { type: 'separator' },
      { commandId: 'page:break', accelerator: 'CommandOrControl+Enter' },
      { commandId: 'page:column-break', accelerator: 'CommandOrControl+Shift+Enter' },
      { type: 'separator' },
      { commandId: 'page:col-1' },
      { commandId: 'page:col-2' },
      { commandId: 'page:col-3' },
      { commandId: 'page:col-left' },
      { commandId: 'page:col-right' },
      { commandId: 'page:col-settings', accelerator: 'CommandOrControl+Option+Enter' },
      { type: 'separator' },
      { commandId: 'page:section-settings' },
    ],
  },
  {
    label: '표',
    items: [
      { commandId: 'table:create' },
      { commandId: 'table:cell-props' },
      { type: 'separator' },
      { commandId: 'table:border-each' },
      { commandId: 'table:border-one' },
      { type: 'separator' },
      { commandId: 'table:insert-row-above' },
      { commandId: 'table:insert-row-below' },
      { type: 'separator' },
      { commandId: 'table:insert-col-left', accelerator: 'Option+Insert' },
      { commandId: 'table:insert-col-right' },
      { type: 'separator' },
      { commandId: 'table:delete-row' },
      { commandId: 'table:delete-col', accelerator: 'Option+Delete' },
      { type: 'separator' },
      { commandId: 'table:cell-split' },
      { commandId: 'table:cell-merge' },
      { commandId: 'table:cell-height-equal' },
      { commandId: 'table:cell-width-equal' },
      { type: 'separator' },
      { commandId: 'table:formula' },
      { commandId: 'table:block-formula' },
      { commandId: 'table:block-sum' },
      { commandId: 'table:block-avg' },
      { commandId: 'table:block-product' },
      { commandId: 'table:thousand-sep' },
      { commandId: 'table:decimal-add' },
      { commandId: 'table:decimal-remove' },
    ],
  },
  {
    label: '도구',
    items: [
      { commandId: 'tool:options', accelerator: 'CommandOrControl+,' },
    ],
  },
  {
    label: '윈도우',
    items: [
      { role: 'minimize' },
      { role: 'zoom' },
      { type: 'separator' },
      { role: 'front' },
    ],
  },
  {
    label: '도움말',
    items: [
      { commandId: 'file:about' },
    ],
  },
];
