const MENU_LABEL_TRANSLATIONS = {
  '파일': 'File',
  '편집': 'Edit',
  '보기': 'View',
  '입력': 'Insert',
  '서식': 'Format',
  '쪽': 'Page',
  '표': 'Table',
  'Hwping 정보': 'About Hwping',
  '환경 설정…': 'Preferences…',
  'Hwping 숨기기': 'Hide Hwping',
  '다른 앱 숨기기': 'Hide Others',
  '모두 보기': 'Show All',
  'Hwping 종료': 'Quit Hwping',
  '새로 만들기': 'New',
  '열기': 'Open',
  '최근 문서': 'Open Recent',
  '최근 문서 없음': 'No Recent Documents',
  '저장': 'Save',
  '다른 이름으로 저장': 'Save As...',
  '편집 용지': 'Page Setup...',
  '인쇄': 'Print',
  '되돌리기': 'Undo',
  '다시 실행': 'Redo',
  '오려 두기': 'Cut',
  '복사하기': 'Copy',
  '붙이기': 'Paste',
  '모양 복사': 'Copy Formatting',
  '지우기': 'Delete',
  '모두 선택': 'Select All',
  '찾기': 'Find',
  '찾아 바꾸기': 'Replace',
  '다시 찾기': 'Find Again',
  '찾아가기': 'Go To...',
  '누름틀 고치기': 'Edit Field',
  '누름틀 지우기': 'Remove Field',
  '확대': 'Zoom In',
  '축소': 'Zoom Out',
  '배율': 'Zoom',
  '쪽 맞춤': 'Fit Page',
  '폭 맞춤': 'Fit Width',
  '조판 부호': 'Show Control Codes',
  '문단 부호': 'Show Paragraph Marks',
  '투명 선': 'Transparent Border',
  '잘림 보기': 'Clip to Page',
  '격자 설정': 'Grid Settings',
  '도구 상자': 'Toolbox',
  '기본': 'Basic',
  '서식': 'Format',
  '도형': 'Shapes',
  '그림': 'Picture',
  '글상자': 'Text Box',
  '필드 입력': 'Insert Field',
  '왼쪽 위': 'Top Left',
  '왼쪽 가운데': 'Middle Left',
  '왼쪽 아래': 'Bottom Left',
  '오른쪽 위': 'Top Right',
  '오른쪽 가운데': 'Middle Right',
  '오른쪽 아래': 'Bottom Right',
  '아래': 'Bottom',
  '문단 띠': 'Paragraph Band',
  '주석': 'Comment',
  '각주': 'Footnote',
  '미주': 'Endnote',
  '문자표': 'Character Map',
  '하이퍼링크': 'Hyperlink',
  '책갈피': 'Bookmark',
  '회전/대칭': 'Rotate / Flip',
  '오른쪽 90° 회전': 'Rotate 90° Right',
  '왼쪽 90° 회전': 'Rotate 90° Left',
  '좌우 대칭': 'Flip Horizontally',
  '상하 대칭': 'Flip Vertically',
  '개체 속성': 'Object Properties',
  '수식 편집': 'Edit Equation',
  '진하게': 'Bold',
  '기울임': 'Italic',
  '밑줄': 'Underline',
  '글자 모양': 'Character Shape',
  '문단 모양': 'Paragraph Shape',
  '문단 번호 모양': 'Paragraph Number Shape',
  '글머리표 모양': 'Bullet Shape',
  '한 수준 증가': 'Increase Level',
  '한 수준 감소': 'Decrease Level',
  '글자 크기 크게': 'Increase Font Size',
  '글자 크기 작게': 'Decrease Font Size',
  '왼쪽 정렬': 'Align Left',
  '가운데 정렬': 'Align Center',
  '오른쪽 정렬': 'Align Right',
  '양쪽 정렬': 'Justify',
  '배분 정렬': 'Distribute',
  '줄 간격 늘림': 'Increase Line Spacing',
  '줄 간격 줄임': 'Decrease Line Spacing',
  '스타일': 'Style',
  '양쪽': 'Both Pages',
  '홀수 쪽': 'Odd Pages',
  '짝수 쪽': 'Even Pages',
  '머리말': 'Header',
  '머리말 편집...': 'Edit Header...',
  '꼬리말': 'Footer',
  '꼬리말 편집...': 'Edit Footer...',
  '머리말/꼬리말 닫기': 'Close Header/Footer',
  '머리말/꼬리말 삭제': 'Delete Header/Footer',
  '이전 머리말/꼬리말': 'Previous Header/Footer',
  '다음 머리말/꼬리말': 'Next Header/Footer',
  '머리말/꼬리말 현재 쪽 감추기': 'Hide Header/Footer on Current Page',
  '새 번호로 시작': 'Restart Numbering',
  '현재 쪽만 감추기': 'Hide This Page Only',
  '쪽 나누기': 'Page Break',
  '단 나누기': 'Column Break',
  '단': 'Columns',
  '하나': 'One',
  '둘': 'Two',
  '셋': 'Three',
  '왼쪽': 'Left',
  '오른쪽': 'Right',
  '다단 설정': 'Column Settings',
  '구역 설정': 'Section Settings',
  '표 만들기': 'Create Table',
  '표/셀 속성': 'Table / Cell Properties',
  '셀 테두리/배경': 'Cell Border / Background',
  '각 셀마다 적용': 'Apply to Each Cell',
  '하나의 셀처럼 적용': 'Apply as Single Cell',
  '위쪽에 줄 추가하기': 'Insert Row Above',
  '아래쪽에 줄 추가하기': 'Insert Row Below',
  '왼쪽에 칸 추가하기': 'Insert Column Left',
  '오른쪽에 칸 추가하기': 'Insert Column Right',
  '줄 지우기': 'Delete Row',
  '칸 지우기': 'Delete Column',
  '셀 나누기': 'Split Cell',
  '셀 합치기': 'Merge Cells',
  '셀 높이를 같게': 'Equalize Cell Height',
  '셀 너비를 같게': 'Equalize Cell Width',
  '계산식': 'Formula',
  '블록 계산식': 'Block Formula',
  '블록 합계': 'Block Sum',
  '블록 평균': 'Block Average',
  '블록 곱': 'Block Product',
  '1,000 단위 구분 쉼표': 'Thousands Separator',
  '자릿점 넣기': 'Insert Decimal Separator',
  '자릿점 빼기': 'Remove Decimal Separator',
};

function resolveMenuLanguage() {
  const override = process.env.HWPING_MENU_LANGUAGE?.trim().toLowerCase();
  if (override?.startsWith('en')) return 'en';
  if (override?.startsWith('ko')) return 'ko';

  const intlLocale = Intl.DateTimeFormat().resolvedOptions().locale?.trim().toLowerCase() ?? '';
  if (intlLocale.startsWith('en')) return 'en';
  if (intlLocale.startsWith('ko')) return 'ko';

  const envLocale = process.env.LANG?.trim().toLowerCase() ?? '';
  if (envLocale.startsWith('en')) return 'en';
  if (envLocale.startsWith('ko')) return 'ko';

  return 'ko';
}

const MENU_LANGUAGE = resolveMenuLanguage();

export function translateMenuLabel(label) {
  if (MENU_LANGUAGE !== 'en') {
    return label;
  }
  return MENU_LABEL_TRANSLATIONS[label] ?? label;
}

const cmd = (commandId, label, options = {}) => ({ commandId, label: translateMenuLabel(label), ...options });
const sep = () => ({ type: 'separator' });
const sub = (label, items) => ({ label: translateMenuLabel(label), items });
const appAction = (action, label, options = {}) => ({ type: 'app-action', action, label: translateMenuLabel(label), ...options });
const recent = () => ({ type: 'recent' });

function hfTemplateItems({ isHeader, applyTo, noun }) {
  const paramsBase = {
    isHeader: String(isHeader),
    applyTo: String(applyTo),
  };

  return [
    cmd(`page:apply-hf-template`, `빈 ${noun}`, {
      params: { ...paramsBase, templateId: '0' },
    }),
    sep(),
    cmd('page:apply-hf-template', '왼쪽 쪽 번호', {
      params: { ...paramsBase, templateId: '1' },
    }),
    cmd('page:apply-hf-template', '가운데 쪽 번호', {
      params: { ...paramsBase, templateId: '2' },
    }),
    cmd('page:apply-hf-template', '오른쪽 쪽 번호', {
      params: { ...paramsBase, templateId: '3' },
    }),
    cmd('page:apply-hf-template', '쪽 번호 + 파일 이름', {
      params: { ...paramsBase, templateId: '4' },
    }),
    cmd('page:apply-hf-template', '파일 이름 + 쪽 번호', {
      params: { ...paramsBase, templateId: '5' },
    }),
    sep(),
    cmd('page:apply-hf-template', '왼쪽 쪽 번호 (굵게)', {
      params: { ...paramsBase, templateId: '6' },
    }),
    cmd('page:apply-hf-template', '가운데 쪽 번호 (굵게)', {
      params: { ...paramsBase, templateId: '7' },
    }),
    cmd('page:apply-hf-template', '오른쪽 쪽 번호 (굵게)', {
      params: { ...paramsBase, templateId: '8' },
    }),
    cmd('page:apply-hf-template', '쪽 번호 + 파일 이름 (굵게)', {
      params: { ...paramsBase, templateId: '9' },
    }),
    cmd('page:apply-hf-template', '파일 이름 + 쪽 번호 (굵게)', {
      params: { ...paramsBase, templateId: '10' },
    }),
  ];
}

export const desktopAppMenuItems = [
  cmd('file:about', 'Hwping 정보', { transport: 'renderer' }),
  cmd('tool:options', '환경 설정…', { accelerator: 'CommandOrControl+,' }),
  sep(),
  appAction('hide', 'Hwping 숨기기'),
  appAction('hide-others', '다른 앱 숨기기'),
  appAction('show-all', '모두 보기'),
  sep(),
  appAction('quit', 'Hwping 종료'),
];

export const desktopMenuGroups = [
  {
    label: '파일',
    items: [
      cmd('file:new-doc', '새로 만들기', { accelerator: 'CommandOrControl+N' }),
      cmd('file:open', '열기', { accelerator: 'CommandOrControl+O', transport: 'main' }),
      recent(),
      cmd('file:save', '저장', { accelerator: 'CommandOrControl+S' }),
      cmd('file:save-as', '다른 이름으로 저장', { accelerator: 'CommandOrControl+Shift+S' }),
      sep(),
      cmd('file:page-setup', '편집 용지', { accelerator: 'F7' }),
      cmd('file:print', '인쇄', { accelerator: 'CommandOrControl+P' }),
    ],
  },
  {
    label: '편집',
    items: [
      cmd('edit:undo', '되돌리기', { accelerator: 'CommandOrControl+Z' }),
      cmd('edit:redo', '다시 실행', { accelerator: 'CommandOrControl+Shift+Z' }),
      sep(),
      cmd('edit:cut', '오려 두기', { accelerator: 'CommandOrControl+X' }),
      cmd('edit:copy', '복사하기', { accelerator: 'CommandOrControl+C' }),
      cmd('edit:paste', '붙이기', { accelerator: 'CommandOrControl+V' }),
      cmd('edit:format-copy', '모양 복사', { accelerator: 'CommandOrControl+Alt+C' }),
      sep(),
      cmd('edit:delete', '지우기', { accelerator: 'CommandOrControl+E' }),
      cmd('edit:select-all', '모두 선택', { accelerator: 'CommandOrControl+A' }),
      sep(),
      cmd('edit:find', '찾기', { accelerator: 'CommandOrControl+F' }),
      cmd('edit:find-replace', '찾아 바꾸기', { accelerator: 'CommandOrControl+F2' }),
      cmd('edit:find-again', '다시 찾기', { accelerator: 'CommandOrControl+L' }),
      cmd('edit:goto', '찾아가기', { accelerator: 'Option+G' }),
      cmd('field:edit', '누름틀 고치기'),
      cmd('field:remove', '누름틀 지우기'),
    ],
  },
  {
    label: '보기',
    items: [
      cmd('view:zoom-in', '확대', { accelerator: 'CommandOrControl+=' }),
      cmd('view:zoom-out', '축소', { accelerator: 'CommandOrControl+-' }),
      sep(),
      sub('배율', [
        cmd('view:zoom-fit-page', '쪽 맞춤'),
        cmd('view:zoom-fit-width', '폭 맞춤'),
        sep(),
        cmd('view:zoom-50', '50%'),
        cmd('view:zoom-75', '75%'),
        cmd('view:zoom-100', '100%', { accelerator: 'CommandOrControl+0' }),
        cmd('view:zoom-125', '125%'),
        cmd('view:zoom-150', '150%'),
        cmd('view:zoom-200', '200%'),
        cmd('view:zoom-300', '300%'),
      ]),
      sep(),
      cmd('view:ctrl-mark', '조판 부호'),
      cmd('view:para-mark', '문단 부호'),
      cmd('view:border-transparent', '투명 선'),
      cmd('view:toggle-clip', '잘림 보기'),
      cmd('view:grid-settings', '격자 설정'),
      sep(),
      sub('도구 상자', [
        cmd('view:toolbox-basic', '기본'),
        cmd('view:toolbox-format', '서식'),
      ]),
    ],
  },
  {
    label: '입력',
    items: [
      cmd('insert:shape', '도형'),
      sep(),
      cmd('insert:image', '그림'),
      cmd('insert:textbox', '글상자'),
      sep(),
      cmd('insert:field', '필드 입력'),
      sep(),
      sub('캡션 넣기', [
        cmd('insert:caption-top', '위'),
        cmd('insert:caption-lt', '왼쪽 위'),
        cmd('insert:caption-lm', '왼쪽 가운데'),
        cmd('insert:caption-lb', '왼쪽 아래'),
        cmd('insert:caption-rt', '오른쪽 위'),
        cmd('insert:caption-rm', '오른쪽 가운데'),
        cmd('insert:caption-rb', '오른쪽 아래'),
        cmd('insert:caption-bottom', '아래'),
        cmd('insert:caption-none', '캡션 없음'),
      ]),
      cmd('insert:para-band', '문단 띠'),
      sep(),
      cmd('insert:comment', '주석'),
      cmd('insert:footnote', '각주'),
      cmd('insert:endnote', '미주'),
      sep(),
      cmd('insert:symbols', '문자표', { accelerator: 'Option+F10' }),
      sep(),
      cmd('insert:hyperlink', '하이퍼링크'),
      cmd('insert:bookmark', '책갈피'),
      sep(),
      sub('회전/대칭', [
        cmd('insert:rotate-cw', '오른쪽 90° 회전'),
        cmd('insert:rotate-ccw', '왼쪽 90° 회전'),
        sep(),
        cmd('insert:flip-horz', '좌우 대칭'),
        cmd('insert:flip-vert', '상하 대칭'),
      ]),
      sep(),
      cmd('insert:picture-props', '개체 속성'),
      cmd('insert:equation-edit', '수식 편집'),
      cmd('insert:caption-toggle', '캡션 넣기'),
      cmd('insert:picture-delete', '개체 지우기'),
    ],
  },
  {
    label: '서식',
    items: [
      cmd('format:bold', '진하게', { accelerator: 'CommandOrControl+B' }),
      cmd('format:italic', '기울임', { accelerator: 'CommandOrControl+I' }),
      cmd('format:underline', '밑줄', { accelerator: 'CommandOrControl+U' }),
      sep(),
      cmd('format:char-shape', '글자 모양', { accelerator: 'Option+L' }),
      cmd('format:para-shape', '문단 모양', { accelerator: 'Option+T' }),
      sep(),
      cmd('format:para-num-shape', '문단 번호 모양'),
      cmd('format:bullet-shape', '글머리표 모양'),
      sep(),
      cmd('format:level-increase', '한 수준 증가', { accelerator: 'CommandOrControl+-' }),
      cmd('format:level-decrease', '한 수준 감소', { accelerator: 'CommandOrControl+=' }),
      sep(),
      cmd('format:font-size-increase', '글자 크기 크게', { accelerator: 'Option+Shift+E' }),
      cmd('format:font-size-decrease', '글자 크기 작게', { accelerator: 'Option+Shift+R' }),
      sep(),
      cmd('format:align-left', '왼쪽 정렬', { accelerator: 'CommandOrControl+Shift+L' }),
      cmd('format:align-center', '가운데 정렬', { accelerator: 'Option+Shift+C' }),
      cmd('format:align-right', '오른쪽 정렬', { accelerator: 'Option+Shift+H' }),
      cmd('format:align-justify', '양쪽 정렬', { accelerator: 'CommandOrControl+Shift+M' }),
      cmd('format:align-distribute', '배분 정렬', { accelerator: 'Option+Shift+D' }),
      sep(),
      cmd('format:line-spacing-increase', '줄 간격 늘림', { accelerator: 'Option+Shift+Z' }),
      cmd('format:line-spacing-decrease', '줄 간격 줄임', { accelerator: 'Option+Shift+A' }),
      sep(),
      cmd('format:style-dialog', '스타일', { accelerator: 'F6' }),
      sep(),
      cmd('format:object-properties', '개체 속성'),
    ],
  },
  {
    label: '쪽',
    items: [
      cmd('page:setup', '편집 용지', { accelerator: 'F7' }),
      sep(),
      sub('머리말', [
        sub('양쪽', hfTemplateItems({ isHeader: true, applyTo: 0, noun: '머리말' })),
        sub('홀수 쪽', hfTemplateItems({ isHeader: true, applyTo: 2, noun: '머리말' })),
        sub('짝수 쪽', hfTemplateItems({ isHeader: true, applyTo: 1, noun: '머리말' })),
        sep(),
        cmd('page:header-create', '머리말 편집...'),
      ]),
      sub('꼬리말', [
        sub('양쪽', hfTemplateItems({ isHeader: false, applyTo: 0, noun: '꼬리말' })),
        sub('홀수 쪽', hfTemplateItems({ isHeader: false, applyTo: 2, noun: '꼬리말' })),
        sub('짝수 쪽', hfTemplateItems({ isHeader: false, applyTo: 1, noun: '꼬리말' })),
        sep(),
        cmd('page:footer-create', '꼬리말 편집...'),
      ]),
      cmd('page:headerfooter-close', '머리말/꼬리말 닫기'),
      cmd('page:headerfooter-delete', '머리말/꼬리말 삭제'),
      cmd('page:headerfooter-prev', '이전 머리말/꼬리말'),
      cmd('page:headerfooter-next', '다음 머리말/꼬리말'),
      sep(),
      cmd('page:hide-headerfooter', '머리말/꼬리말 현재 쪽 감추기'),
      cmd('page:new-page-num', '새 번호로 시작'),
      cmd('page:hide-current', '현재 쪽만 감추기'),
      sep(),
      cmd('page:break', '쪽 나누기', { accelerator: 'CommandOrControl+Enter' }),
      cmd('page:column-break', '단 나누기', { accelerator: 'CommandOrControl+Shift+Enter' }),
      sep(),
      sub('단', [
        cmd('page:col-1', '하나'),
        cmd('page:col-2', '둘'),
        cmd('page:col-3', '셋'),
        cmd('page:col-left', '왼쪽'),
        cmd('page:col-right', '오른쪽'),
        sep(),
        cmd('page:col-settings', '다단 설정', { accelerator: 'CommandOrControl+Option+Enter' }),
      ]),
      sep(),
      cmd('page:section-settings', '구역 설정'),
    ],
  },
  {
    label: '표',
    items: [
      cmd('table:create', '표 만들기'),
      cmd('table:cell-props', '표/셀 속성'),
      sep(),
      sub('셀 테두리/배경', [
        cmd('table:border-each', '각 셀마다 적용'),
        cmd('table:border-one', '하나의 셀처럼 적용'),
      ]),
      sep(),
      cmd('table:insert-row-above', '위쪽에 줄 추가하기'),
      cmd('table:insert-row-below', '아래쪽에 줄 추가하기'),
      sep(),
      cmd('table:insert-col-left', '왼쪽에 칸 추가하기', { accelerator: 'Option+Insert' }),
      cmd('table:insert-col-right', '오른쪽에 칸 추가하기'),
      sep(),
      cmd('table:delete-row', '줄 지우기'),
      cmd('table:delete-col', '칸 지우기', { accelerator: 'Option+Delete' }),
      sep(),
      cmd('table:cell-split', '셀 나누기', { accelerator: 'S' }),
      cmd('table:cell-merge', '셀 합치기', { accelerator: 'M' }),
      cmd('table:cell-height-equal', '셀 높이를 같게', { accelerator: 'H' }),
      cmd('table:cell-width-equal', '셀 너비를 같게', { accelerator: 'W' }),
      sep(),
      cmd('table:formula', '계산식'),
      cmd('table:block-formula', '블록 계산식'),
      cmd('table:block-sum', '블록 합계', { accelerator: 'CommandOrControl+Shift+S' }),
      cmd('table:block-avg', '블록 평균', { accelerator: 'CommandOrControl+Shift+A' }),
      cmd('table:block-product', '블록 곱', { accelerator: 'CommandOrControl+Shift+P' }),
      cmd('table:thousand-sep', '1,000 단위 구분 쉼표'),
      cmd('table:decimal-add', '자릿점 넣기'),
      cmd('table:decimal-remove', '자릿점 빼기'),
    ],
  },
];
